### ISSUE TITLE
handle noqa comment on multi line import

### ISSUE THREAD

**Issue by xrmx** [charliermarsh/ruff#1052]
In the following example where  something is imported but not used:

```
from foo import (  # noqa
    bar,
    baz,
)
```
flake8 applies the noqa to each import line but ruff 0.0.158 instead warns with `F401` for each line.

**Comment by charliermarsh** [comment]
I'd like to make some improvements to the `noqa` system, and those improvements should enable this or something like it.

(Flake8 supports this because it locates every individual unused member error on the `from foo import (` line, which has a few downsides: you don't get individual span highlighting for individual members, there's no way to ignore _one_ unused member but not others.)

**Comment by pradyunsg** [comment]
FWIW, I hit this while looking at replacing pip's use of `flake8` with `ruff`. 😅

**Comment by charliermarsh** [comment]
😭 Everyone wants this! I need to just bite the bullet and support it.

**Comment by charliermarsh** [comment]
I will try to fix this tomorrow.

**Comment by charliermarsh** [comment]
This should be live shortly. [v0.0.203](https://github.com/charliermarsh/ruff/releases/tag/v0.0.203) is building now. Would love to know if it works for you (or doesn't).

**Comment by TylerYep** [comment]
Fixed for me, thanks!
