### ISSUE TITLE
Replace vendored RustPython code to dependency call

### ISSUE THREAD

**Issue by youknowone** [charliermarsh/ruff#1115]
I found ruff has a vendored code from RustPython
https://github.com/charliermarsh/ruff/tree/main/src/vendored

Do you want to make me to turn them pub in RustPython and refactor to reusable out of RustPython?

**Comment by charliermarsh** [comment]
@youknowone - Yeah! Would love to remove that vendored code.

**Comment by charliermarsh** [comment]
\cc @olliemath in case there's other context on how the code changed when ported over (IIRC the context was well-captured in the relevant PRs though)

**Comment by olliemath** [comment]
Yeah, would be good to remove the vendored code. It's mostly there since it was an issue pulling in a large crate like rustpython-vm as a dependency (even if the methods were public). Since none of the code we use references the VM it could live somewhere else.

With the exception of clippy fixes, the changes to the code are just removals (remove references to the VM, remove dead code etc).
