### ISSUE TITLE
E501 error with strings that contains unicode

### ISSUE THREAD

**Issue by keul** [charliermarsh/ruff#1123]
Non sure if this an issue or a "by design" behaviour: I get a

```
haunts/spreadsheet.py:226:1: E501 Line too long (105 > 100 characters)
```

The line itself is less than 100 chars long (my custom `line-length` in .toml), but I have a string with emoji chars there:

```python
                f"⚠️ ⚠️ ⚠️ - There are…"
```

**Comment by charliermarsh** [comment]
Would you mind posting the full line?

**Comment by keul** [comment]
This is another example, but I post these just for reference. Looking at this gain: it seems is not a ruff issue. I didn't noticed that also VsCode count these chars a 2.

For reference:

```python
        click.echo(
            Back.YELLOW
            + Fore.BLACK
            + (
                f"⚠️ ⚠️ ⚠️ - There are {len(warn_lines)} lines with warnings. Please check them. ⚠️ ⚠️ ⚠️ "
            )
            + Style.RESET_ALL
        )
```

I get:

```
E501 Line too long (107 > 100 characters)
```

Sorry for the noise!

**Comment by charliermarsh** [comment]
No prob! Yeah Unicode characters are tricky. We do count "characters" and not bytes explicitly (via the Rust standard library), but it's not always intuitive, I think...

**Comment by lengau** [comment]
Sorry to necro a week-old thread but I'm a big unicode nerd who happened upon this thread during an unrelated search about E501. I'm adding this purely for the sake of nerdy interest.

`⚠️` is actually two unicode codepoints. Specifically, it's code point [26A0](https://util.unicode.org/UnicodeJsps/character.jsp?a=26A0) for the warning sign and code point [FE0F](https://util.unicode.org/UnicodeJsps/character.jsp?a=FE0F), variation selector. 

Codepoint 26A0 on its own is `⚠`, which looks the same but without the pretty colours of an emoji that the variation selector provides. Or, from a Python terminal:

```
>>> len('⚠️')
2
>>> len('⚠')
1
```

Just to add to the confusion, in UTF-8, ⚠️ is actually 6 bytes long. (Each codepoint is 3 bytes).

I suppose one *could* argue that what we care about here is the number of [graphemes](https://en.wikipedia.org/wiki/Grapheme) rather than bytes or code points, and the [unicode-segmentation](https://crates.io/crates/unicode-segmentation) crate can count graphemes, but that's not without its own costs (mostly performance, but also potentially its own "huh?" moments since the way it's currently counted aligns with Python's `len`).

**Comment by charliermarsh** [comment]
Always appreciate a clarification from someone who knows way more than me about a topic like this :)

**Comment by keul** [comment]
@lengau thanks for the spelunking! This is probably why my terminal has some issues rendering the ⚠️ (I've to separate multiple ones with a blank space) while ⚠ is OK!
