### ISSUE TITLE
Autofix F541 (f-string without any placeholders)?

### ISSUE THREAD

**Issue by keul** [charliermarsh/ruff#1125]
I think that a string like:

```python
f"%H:%M"
```

Which reports:

```
F541 f-string without any placeholders
```

Can be automatically fixed by the ``--fix`` option without any side effect.

**Comment by harupy** [comment]
@charliermarsh Can I work on this?

**Comment by charliermarsh** [comment]
@harupy - Of course, go for it!

It might be easiest to go through LibCST since there are a lot of cases to handle and f-strings are kind of an oddity (by the time you get the AST, the parser has already combined some of the substrings).

**Comment by harupy** [comment]
@charliermarsh Just removing `f` doesn't work?

**Comment by harupy** [comment]
I see, just removing the top `f` doesn't work in this case:

```
x = (
    f"a"
    f"b"
    "c"
)
```

**Comment by charliermarsh** [comment]
Yeah exactly. Implicit string concatenations get transformed by the parser. (If any segment has an f prefix, the whole thing becomes a JoinedStr; but consecutive non-f segments get collapsed.)

**Comment by niccolomineo** [comment]
Hi there, I am getting this false positive:

```
f"{myfunc():.1f}"
```

**Comment by charliermarsh** [comment]
@niccolomineo - This was fixed in v0.0.205! Let me know if you continue to see it but I just tested it myself.

**Comment by niccolomineo** [comment]
@charliermarsh yeah, I have 0.0.205 installed but it still pops up.

Anyways, thank you for the ground you're covering with this module, it's nothing short of amazing!

**Comment by charliermarsh** [comment]
Yeah the bundled version might have that error. I can cut a new pre-release today! (And thank you, that means a lot, truly!)

**Comment by charliermarsh** [comment]
I cut a new pre-release. If you switch to the Ruff extension pre-release, you should get stuff v0.0.206 by default!

**Comment by harupy** [comment]
@charliermarsh I'm implementing autofix for F541 and wanted to hear your thoughts on this approach. Let's say we have an implicitly-concatenated string that contain both f-strings and plain strings:

```python
(
  f""
  ""
  rf""
)
```

We can locate each f-string token and f-prefix position using RustPython's tokenizer. Once we locate them, we can raise F541 on **each token**. To fix them, we can apply `Fix::deletion` on each f-prefix location. Here's a demo:


https://user-images.githubusercontent.com/17039389/210193377-b1426cd1-8f9f-42af-b25b-a5cea5ab5bd3.mov

**Comment by marscher** [comment]
good job! Thank you! :+1:

**Comment by harupy** [comment]
We can extend the approach above to find useless f-strings in an implicitly-concatenated `JoinedStr` containing `FormattedValue`s.

```python
(
  f"abc"  # <- we can locate this
  f"{x}"
)
```

1. Tokenize the string into tokens.
2. Parse each token and check whether they contain `FormattedValue`.

However, this may lead to bad performance due to tokenization and reparsing.

**Comment by charliermarsh** [comment]
@harupy - I think these approaches make sense! Maybe we start by only enforcing this in the first case? So that we don't have to tokenize every f-string (only those that don't contain any placeholders)?

_Arguably_, this is actually desirable:

```py
(
  f"abc"
  f"{x}"
)
```

Since with this version, you have different indentation levels for each string, you have to keep track of which parts have a prefix and which don't, etc.:

```py
(
  "abc"
  f"{x}"
)
```
