### ISSUE TITLE
[bug] Ruff reports fixable errors even after `--fix`

### ISSUE THREAD

**Issue by smackesey** [charliermarsh/ruff#1132]
I don't know exactly under what situations this occurs but I see this fairly often:

```
ruff --extend-ignore=F401 --fix .
Found 23 error(s) (6 fixed, 17 remaining).
...
2 potentially fixable with the --fix option.
```

Seems like `ruff` should fix everything fixable in a single pass?

**Comment by charliermarsh** [comment]
There are some error classes that are considered fixable, but for which certain cases can't be autofixed. For example, ensuring that we have a single blank line in a docstring after the first summary line. We can fix that in some cases, but not others -- and so the rule is considered "fixable", but might fail to fix in some cases.

I think this message should be changed though. It used to be the case that we'd do one fix pass, which could leave you with more fixable errors, and so this message would make sense (since you might need to re-run `ruff --fix`). We now fix iteratively until the code stabilizes, so it's never the case that calling `ruff --fix .` will yield errors that are actually fixable.

Anyway, that's all to say: we shouldn't show you that message if you're already using `--fix`.

**Comment by smackesey** [comment]
Related: IMO it should say `(0 fixed)` is you run `ruff --fix` and it doesn't fix anything. Otherwise it's kind of confusing and some users might wonder if there's a bug or their `--fix` didn't register.

```
$ ruff --fix --extend-ignore=F401 .
Found 2 error(s).
python_modules/automation-internal/automation_internal/cloud/check/old_images.py:79:9: PLR1722 Consider using `sys.exit()`
python_modules/automation-internal/automation_internal/infra/terragrunt.py:318:5: PLR1722 Consider using `sys.exit()`
```
