### ISSUE TITLE
E711: `--fix` doesn't always fix and messes up quotes

### ISSUE THREAD

**Issue by mikeroll** [charliermarsh/ruff#1237]
`ruff` correctly identifies the issues with the code below 
```py
def test():
    assert "string" == None  # E711
    assert 42 == None  # E711
    assert foo("string") == None  # E711
```

but `ruff --fix` here is far from perfect:
```py
def test():
    assert 'string' == None  # suddenly single quotes and no fix
    assert 42 == None  # no fix
    assert foo('string') is None  # fixed, but why single quotes?
```
Tested on 0.178.

**Comment by charliermarsh** [comment]
Huh, wait, this actually does do the right thing for me (modulo the single quotes) -- I get this output:

```py
def test():
    assert 'string' is None  # E711
    assert 42 is None  # E711
    assert foo('string') is None  # E711
```

Any idea on the discrepancy?

**Comment by mikeroll** [comment]
Weird, I have checked again just now in a fresh venv.
```
❯ cat test.py
def foo(x):
    return None

def test():
    assert "string" == None
    assert 42 == None
    assert foo("string") == None

❯ python -V; ruff --version
Python 3.10.6
ruff 0.0.182

❯ ruff --fix test.py; cat test.py
Found 202 error(s) (200 fixed, 2 remaining).
test.py:5:24: E711 Comparison to `None` should be `cond is None`
test.py:6:18: E711 Comparison to `None` should be `cond is None`
def foo(x):
    return None

def test():
    assert 'string' == None
    assert 42 == None
    assert foo('string') is None

**Comment by charliermarsh** [comment]
I wonder if there are competing error fixes that are causing a conflict here.

**Comment by charliermarsh** [comment]
Ah, ok, I think the issue here is that we have two conflicting rules (though Flake8 raises the same errors).

Before the `is` fix, we have:

```
foo.py:5:21: E711 comparison to None should be 'if cond is None:'
foo.py:6:15: E711 comparison to None should be 'if cond is None:'
```

And once that's autofixed, we get:

```
foo.py:5:12: F632 use ==/!= to compare constant literals (str, bytes, int, float, tuple)
foo.py:6:12: F632 use ==/!= to compare constant literals (str, bytes, int, float, tuple)
```

So we just keep autofixing back and forth (hence "200 fixed").

**Comment by charliermarsh** [comment]
I think `E711` should be disabled when the other comparator is a literal.

**Comment by charliermarsh** [comment]
Thanks for this!

**Comment by charliermarsh** [comment]
(Will fix today.)

**Comment by mikeroll** [comment]
Oh nice, thanks a lot!

Also a reminder for me to include the configuration in bug reports, I do have both E and F enabled.

**Comment by charliermarsh** [comment]
It's kind of tricky because the rules are fundamentally in conflict :)

Take, for example, `if "abc" is None: pass`.

`F632` says we should change this to `if "abc" == None: pass`, since comparing to `None` with `==` like that is a `SyntaxWarning` (which I believe will be an error in the future). But `if "abc" == None: pass` triggers `E711`.

The fix I settled on is to avoid auto-fixing `E711` and `E712` errors that would in turn _cause_ an `F632`, which I think is the best compromise. So, in this case, we _would_ change it to `if "abc" == None: pass` to avoid the syntax error; but you'd then be presented with an `E711` that you'd have to fix yourself or disable.
