### ISSUE TITLE
Files that are ignored in config are checked when passed explicitly on the command line

### ISSUE THREAD

**Issue by cpcloud** [charliermarsh/ruff#1301]
When a file is ignored in config, but then explicitly passed on the command line `ruff` checks it anyway.

Here's a reproducing [gist](https://gist.github.com/cpcloud/fcd285f87486a8bc712911ffc289310c).

This makes running `pre-commit run --all-files` (using the official `ruff` pre-commit hook) fail, because files are passed to `ruff` explicitly.

Ideally, the config is followed no matter what's passed on the command line in this case.

**Comment by charliermarsh** [comment]
Ah yeah, this is actually intentional and is the same strategy used by Black. In short, if you pass a file directly to `ruff`, we don't ignore it, which is almost always desirable, except in the case of `pre-commit`.

In [v0.0.189](https://github.com/charliermarsh/ruff/releases/tag/v0.0.189), I added a `--force-exclude` boolean flag that disables that behavior, and causes Ruff to exclude files regardless of whether they're passed directly.

You should be able to either set that in your `pyproject.toml`, or better yet pass it as an arg to the pre-commit invocation.

**Comment by cpcloud** [comment]
Excellent, thank you!
