### ISSUE TITLE
How do you plan on keeping up with new rules/fixes in core ?

### ISSUE THREAD

**Issue by Crocmagnon** [charliermarsh/ruff#2322]
This is more a general question rather than a feature request/bug report:

How do you plan on keeping up to date with evolving projects you reimplemented in core, like pyupgrade for example?

**Comment by charliermarsh** [comment]
The goal is to maintain parity as those projects evolve, to the degree that we can. We've already reimplemented some upstream fixes from `flake8-bugbear`, for example.

Many of the plugins we've reimplemented, though, are pretty "stable", in that they tend not to add many additional rules. E.g., many of them haven't seen new releases in the past few years. That's not true of _all_ of them, but at least a handful.

`pyupgrade` is maybe an interesting case, because we don't _really_ support pre-Python 3.7 code. So I'd probably not prioritize anything that was added to `pyupgrade` that was focused on 2-to-3 conversions. (We do have some of that, like `six` import removal, but in hindsight I wouldn't have prioritized adding it.) On the other hand, there's a lot of stuff in `pyupgrade` that's useful for the ongoing maintenance of Python 3 code, like the type annotation rules. So I _would_ pull in new rules of that nature.

**Comment by charliermarsh** [comment]
Hopefully that answers your question, but obviously happy to field any follow-ups :)

**Comment by Crocmagnon** [comment]
Great! Thanks for your answer 😊

Yeah my question about pyupgrade was more focused on the ongoing development for new Python versions as I don’t see this tool be « finished » like maybe isort or some other could be (I mean once you’ve sorted your imports everything else is bug fixing, … right ? 😁)

And thanks for ruff! It’s an amazing piece of software 😊 I incorporated it in my own projects coming from flakeheaven and the transition was smooth. I don’t have large codebases but it feels a lot snappier already.

**Comment by charliermarsh** [comment]
Amazing, so glad to hear that it's working for you :)
