### ISSUE TITLE
[Question] is it possible to run ruff only on edited lines of a branch/commit?

### ISSUE THREAD

**Issue by tharwan** [charliermarsh/ruff#2472]
Similar to the what darker does for black, it would be very nice for introducing ruff to a code base to only apply it to changed lines.

**Comment by charliermarsh** [comment]
Hey! It's not possible right now -- some things like this have come up in #1149, #1931, #2189. I'm hesitant to support it since it's a hard feature to get right. I haven't used `darker`, but the problem with applying that methodology to Ruff (IIUC) is that unlike code formatting, linter errors are not always localized: you could remove an import from one part of the file, and it could cause an error in an unchanged part of the file.

One alternative (not what you're looking for, but thought I'd mention it) is that you can run `ruff --add-noqa /path/to/file.py` and it will add `noqa` suppressions to any lines that fail. I know this won't work in all cases, but it's an option.

**Comment by tharwan** [comment]
Thanks for the quick reply! I guess another option would be to include all files touched by  a commit.

**Comment by charliermarsh** [comment]
Yeah definitely! Although I feel like there are probably ways to do that via Git commands and piping, and if they're workable, it's a bit easier than building logic into Ruff.

In Flake8, they suggest this as an alternative to their `--diff` functionality which was deprecated:

```
git diff --name-only -z --diff-filter=d -- '*.py' | xargs -0 flake8 or utilize pre-commit run --from-ref=... --to-ref=...
```

But I haven't tried it.

**Comment by itolosa** [comment]
I guess another brute force solution would be to run ruff before and after the changes and in some sort do a set difference:

introducedErrors = errorsAfter - errorsBefore

**Comment by victor-varjo** [comment]
> I guess another brute force solution would be to run ruff before and after the changes and in some sort do a set difference:
> 
> introducedErrors = errorsAfter - errorsBefore

And make it aware of file renames.
