### ISSUE TITLE
Add a flag to tell users which files were fixed, and via which rules

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#2661]

**Comment by henryiii** [comment]
I'd prefer it on every Ruff invocation - it's just as important as the list of things that are fixable, and no more verbose than that list if you didn't pass the `--fix`. Knowing what it changed is just as important as what still needs to be done, and I'd just run it again if I wanted only the remaining fixable items (I do that with Rubocop, actually). But I'm totally fine with it being a flag too, I'd just add it to pre-commit's args. I woudn't want too much extra info, though - the file, line number, code, and reason for the unfixed checks is just about perfect for the fixed checks too.

Recent example: I added a noqa for a problem, then ran Ruff:

```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1
- files were modified by this hook

tests/test_command.py:413:5: SIM117 [*] Use a single `with` statement with multiple contexts instead of nested `with` statements
Found 2 errors (1 fixed, 1 remaining).
```

It deleted the noqa I added (since I missed by one line, I put it on the inner with instead of the outer with). But I can't tell that it did that from the output above; if I got the RUF00x noqa removal fix listed as "fixed", it would be much clearer what happened.
