### ISSUE TITLE
feat: support for `flake8-length`

### ISSUE THREAD

**Issue by aarnphm** [charliermarsh/ruff#2683]
Hi all, thanks for an amazing linter.

I'm just wondering if having support for [flake8-length](https://pypi.org/project/flake8-length/) is feasible with ruff. We are currently using this for exception message (where it still throw E501 even though we have disabled E501 globally).

This tool is supported with pylint iirc (as we are in the process of migrating away from pylint to ruff).

I would love to help if the team sees fit.

**Comment by aarnphm** [comment]
> Do you have an example of something that flake8-length permits, but Ruff flags as a violation?

So in `flake8-length`, you can set `max-line-length` as a soft limit. So the following example

<img width="1748" alt="Screenshot 2023-02-09 at 05 30 33" src="https://user-images.githubusercontent.com/29749331/217826166-ada17965-93ed-41fd-8455-6afcdd4b5648.png">

Ruff flags as a E501 violation. This is expected as I set the line-length to be similar of black.

The current solution that we are using is to disable E501 globally.

**Comment by charliermarsh** [comment]
It looks like the main difference is that `flake8-length` skips single-line strings and a variety of comments. I'd probably rather not support that for now since there's also been a request to implement flake8-bugbear's line-length rule (which includes a "tolerance"), and I'm hesitant to have so many different line-length rules.

**Comment by aarnphm** [comment]
Sounds good to me. I think when flake8-bugbear is supported then I will use that instead then.

Closing for now.
