### ISSUE TITLE
Python 2 style type hints are removed automatically by the autofix for F401

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [charliermarsh/ruff#2685]
On the following snippet:
```python
from typing import List, Tuple

number_to_string = [] # type: List[Tuple[int, str]]
```
The typing import are removed automatically. Note, that autoflake > 2 also does this.

Not a barrier to adoption as there's a simple workaround : Using autoflake < 2.0.0, and ``--unfixable F401`` in ruff.

**Comment by charliermarsh** [comment]
Yeah I need to make some kind of formal decision on Python 2-style type hints, it's come up a couple times and we don't support them, but I'm not certain if we should or not.

**Comment by Pierre-Sassoulas** [comment]
If there was an integrated fix to upgrade to python3 typing (like [com2ann](https://github.com/ilevkivskyi/com2ann)) it would be a really understandable decision not to support python 2 type hint, as python 3.5 has been EOL for a really long time by now. Or users can do it with ``com2ann`` on their own directly, this is a one time thing (?)

**Comment by tmke8** [comment]
Note that there are still two places that can only be annotated with comments: for-loops and with-statements:
```python
from typing import Any

it: Any
for x in it:  # type: int
    reveal_type(x)  # Revealed type is "builtins.int"
    
con: Any
with con as y:  # type: str
    reveal_type(y)  # Revealed type is "builtins.str"
```
(mypy playground link for the above code: https://mypy-play.net/?mypy=latest&python=3.11&gist=96217be4d93348ee591988a5744c1a60 )

However, I've never actually seen this used in real code, so not sure how important it is.

**Comment by charliermarsh** [comment]
In the interest of cutting corners 😅 my general philosophy has been to avoid one-time 2-to-3 migration rules -- in part because they add complexity, but also, they tend to be a little under-tested since they're used less frequently in the wild given their one-time nature.

For example, we removed the `six` import rewrites, since `pyupgrade` can be used to do those one-time, and probably had a stabler implementation than ours which likely wasn't run on "real" code with the same frequency. (I see these kinds of rules as different from those that are useful for writing Python 3 code on an ongoing basis, like (e.g.) type annotation rewrites that prefer the builtin generics over `typing.List` and friends.)

So my instinct here is to avoid supporting comment annotations, and also to defer implementing `com2ann` in the hopes that users would run that tool one-time.

**Comment by charliermarsh** [comment]
As always I'm totally open to being convinced otherwise, but I'm gonna call it "decided" for now.
