### ISSUE TITLE
Implement A001, A002 (flake8-builtins)

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#275]
See: https://github.com/gforcada/flake8-builtins

**Comment by sobolevn** [comment]
Hi, I would like to work on it :)

**Comment by charliermarsh** [comment]
Awesome! Feel free to punt on the autofixing if it gets tricky. The autofix API still relies on manual token parsing.

**Comment by sobolevn** [comment]
I am very reluctant about adding autofixing to naming rules. Naming should be done by humans.
`type` -> `type_` is just not good enough.

Moreover, autofixing naming can actually break stuff. Imagine that some `copyright` or `type` name is actually required.

**Comment by adriangb** [comment]
For the little my opinion is worth I regularly do stuff like `id = ...` or `type = ...` because I think `id_ = ...` or `tp = ...` convolutes the name and my type checker will yell at me already if I try to do `id = 1; id(...)`. This is especially true in small self contained functions (that's what namespaces are for). The auto fix would break my code in strange ways. And it's very possible the person running the auto fix is not me.

**Comment by charliermarsh** [comment]
Sorry, yes, this rule absolutely should not have autofix. (I wrote that comment from my phone and had #273 in my head.)

**Comment by charliermarsh** [comment]
Resolved by #284!

**Comment by sobolevn** [comment]
Thanks! I will work on something else tomorrow :)

**Comment by charliermarsh** [comment]
Thank _you_!

P.S. Now that you've gone through the end-to-end process of implementing a rule, feel free to propose any broader refactors that might make that process easier / saner.
