### ISSUE TITLE
PT006 fix adds unneeded parenthesis

### ISSUE THREAD

**Issue by frenck** [charliermarsh/ruff#2918]
PT006 seems to add additional parenthesis in case the string is already wrapped in a parenthesis to split it into multiple lines.

![image](https://user-images.githubusercontent.com/195327/219019029-fc0a9da7-14e5-41b9-8580-987d0dc0cd90.png)

```py
@pytest.mark.parametrize(
    (
        "create_backup_error, create_backup_calls, "
        "update_addon_error, update_addon_calls, "
        "error_message"
    ),
	[...]
)
```

Results in:

```py
@pytest.mark.parametrize(
    (
        (
            "create_backup_error",
            "create_backup_calls",
            "update_addon_error",
            "update_addon_calls",
            "error_message",
        )
    ),
    [...]
)
```

Expected:

```py
@pytest.mark.parametrize(
    (
        "create_backup_error",
        "create_backup_calls",
        "update_addon_error",
        "update_addon_calls",
        "error_message",
    ),
    [...]
)
```

**Comment by charliermarsh** [comment]
Thanks :)

**Comment by charliermarsh** [comment]
Ohh interesting, because the expression is itself parenthesized already. Hmm...

**Comment by dhruvmanila** [comment]
So, I was looking at the recent commit (https://github.com/charliermarsh/ruff/commit/abaf0a198d9d2cebefd5c029bb271be1a3498f20) and thought of a similar approach in solving this problem.

The indexer will collect all the ranges for a pair of parenthesis (`(` to `)`). Then, while trying to generate a fix for the above case, we'll check how many ranges does the string expression range belongs to. If the value is 2, we won't add the parenthesis otherwise we will.

I'm not sure if you've any other solution in mind so just thought to share this.

**Comment by dhruvmanila** [comment]
Actually, I've a better solution in mind, will try to fix it by tonight.

**Comment by frenck** [comment]
Thanks, @dhruvmanila 👍 

../Frenck

**Comment by charliermarsh** [comment]
Another all-star contribution from @dhruvmanila :)

**Comment by dhruvmanila** [comment]
> Another all-star contribution from @dhruvmanila :)

Thanks for your kind words! Always happy to help wherever I can 😄
