### ISSUE TITLE
COM812: correct?

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#3303]
```python
foo = tuple
print(
    list(foo(1, 2, 3, 4))
    + list(foo(6, 7, 8, 9))
    + list(foo(6, 7, 8, 9))
    + list(foo(6, 7, 8, 9))
    + list(foo(6, 7, 8, 9))
)
```
tells me: `foo.py|7 col 28 error| COM812 [*] Trailing comma missing` which looks strange.

Also `black` wouldn't change the code:
```console
$ black --diff foo.py
All done! ✨ 🍰 ✨
1 file would be left unchanged
```

is that trailing comma correct?

**Comment by bluetech** [comment]
It is technically correct. I noticed myself many cases where a trailing comma is technically correct but undesirable, like this one, but I can't quite phrase the correct heuristic. It definitely involves single-argument function calls, but sometimes I do want a trailing comma for these...

> Also black wouldn't change the code

Does black add trailing commas at all?

If a trailing comma is present in this example, does black *remove* it?

**Comment by spaceone** [comment]
no, `black` doesn't remove it.
The trailing commata is sometimes a marker in black to split things into multiline.
but that is also probably not related to this rule.

**Comment by bluetech** [comment]
So black can't guide us on the desired heuristic here.

I myself turned off COM812 due to these two cases in Django code:

```py
results = list(
    # ... Long queryset ...
    xxx   # <-- Don't want comma here
)
```

```py
class MyModel(models.Model):
    my_field = models.CharField(
        ...,
        help_text=_(
             "Long help text "
             "Here"   # <-- Don't want comma here
        ),
    )
```

One heuristic is to not add trailing comma on single-argument function calls, but this is not 100%.

Another option is to add a setting for function names to which trailing comma shouldn't be added (`list` and `_` in my case), but would be better if it's not needed.

**Comment by bluetech** [comment]
Some discussion in flake8-commas issue: https://github.com/PyCQA/flake8-commas/issues/59

**Comment by JonathanPlasse** [comment]
In which condition would having a comma for single argument in function be desirable?

**Comment by bluetech** [comment]
Any function that can have more arguments. If we stay in DJango just for the example

```py
my_field = models.CharField(
    _("My field")
)
```

I'd want a trailing comma in this case. But not having one is better than disabling COM802 entirely.

**Comment by charliermarsh** [comment]
Yeah it's very reasonable to have a trailing comma for a single-argument function IMO.

Black does add a trailing comma if you have more than one argument -- so it doesn't add one after `list(...)` here:

```py
x(
    list(
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        812093129032910381290321903219031,
        812093129032910381290321903219031,
    )
)
```

But it does add one after `y` here:

```py
x(
    list(
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        812093129032910381290321903219031,
        812093129032910381290321903219031,
    ),
    y
)
```

**Comment by charliermarsh** [comment]
We could avoid adding a trailing comma for single-argument functions that match certain expressions... like binary expressions, etc.

**Comment by Avasam** [comment]
Whilst I don't use black, I do use [`add-trailing-comma`'s multiline method invocation style](https://github.com/asottile/add-trailing-comma#multi-line-method-invocation-style----why), which is worth taking a look at.

**Comment by charliermarsh** [comment]
Looks like `add-trailing-comma` _does_ add a comma in this case, like Ruff (but avoids trailing commas for functions with trailing `*args` or `**kwargs`).

**Comment by Avasam** [comment]
> [...] (but avoids trailing commas for functions with trailing `*args` or `**kwargs`).

To be exact, [it only does so for python 3.5](https://github.com/asottile/add-trailing-comma#trailing-commas-for-function-definitions-with-unpacking-arguments), [so does Black](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas), and because that'd be a syntax error. On recent python versions everything multiline gets a trailing comma. I don't think Ruff is even concerned about EOL versions.

The reasoning `add-trailing-comma` uses on reducing lines in a diff is sound to me. And the reason why I want trailing commas in the first place.
I can see the argument for aesthetics on single-parameters. Even Black didn't take a hard stance here (which I find surprising).

Since this is more or less all gonna end up being the same rule in Ruff, maybe this should be left to the user's choice in whatever config system Ruff is going towards (insert trailing commas for single multiline items, remove trailing commas for single multiline items, or leave as-is with a "[magic trailing comma](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma)" like black does)

**Comment by charliermarsh** [comment]
Yeah right now the Ruff formatter uses similar trailing comma rules to Black. I think I'm fine with us inserting a trailing comma even for single-argument calls in COM812 right now -- it can look odd in some cases, but I think it's "correct" and matches the intent of the rule, so I'll close this.

**Comment by benjamin-kirkbride** [comment]
![image](https://github.com/astral-sh/ruff/assets/3373830/52daca39-0e45-4b96-b40a-75148f23f3ac)

is this related?
