### ISSUE TITLE
Rules mentioned in the changelog missing

### ISSUE THREAD

**Issue by xmatthias** [charliermarsh/ruff#3355]
Version: ruff 0.0.254
the [changelog for 0.0.254](https://github.com/charliermarsh/ruff/releases/tag/v0.0.254) mentions several (great!) new rules (E211, E225, E226, E227, E228) have been added.

These seem to be missing from the documentation (they should be in the screenshot below - but also a Search doesn't find them) - and are also not applied when trying to see if they still work and are active.

Have these been disabled / removed temporarily, or is there something wrong with this / my install

![image](https://user-images.githubusercontent.com/5024695/223029056-58f7d01d-6e5b-4043-98e0-37c73f6f71d8.png)

**Comment by charliermarsh** [comment]
Ah yeah, sorry about that. This is just a confusion in messaging -- we've implemented those rules, but they're currently behind a feature flag, so they're not accessible from the production build.

I want all of the remaining pycodestyle rules to go out in a single coordinated release, since it's arguably a 'breaking' change for users (it'll enable a bunch of previously non-existent rules for any users that enable the `E` category).

There are about 10 more rules to go, hopefully in the next week or two but don't hold me to it :)

**Comment by xmatthias** [comment]
Great to hear! 

(and thanks for this great project) 💯
