### ISSUE TITLE
Use `CI_PROJECT_DIR`-relative paths for GitLab annotations

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#3443]
At least for Gitlab [`path` should be relative](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool) to the `CI_PROJECT_DIR` location. With this implementation links in widgets are broken.

_Originally posted by @Agalin in https://github.com/charliermarsh/ruff/issues/1837#issuecomment-1464014758_

**Comment by Agalin** [comment]
I'd say there are two options:
* Make it relative to the mentioned variable if present - but what happens if it's not defined?
* Keep paths just relative. I'm not familiar with Github's directory changing but I see no reason why toll cannot be called from a parent directory. It's already possible to use a config from subdirectory and select only subdir files for scan.
