### ISSUE TITLE
Flake8 supports `# noqa: E50`1 inside multiline strings

### ISSUE THREAD

**Issue by ghuls** [charliermarsh/ruff#375]
Flake8 supports `# noqa: E50`1 inside multiline strings.

Ruff README says that is has to be after. Will the former be ever supported?
```
"""Lorem ipsum dolor sit amet.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
"""  # noqa: E501
```

**Comment by charliermarsh** [comment]
Ruff actually used to support this but I removed it to simplify the code. I would consider re-adding it though. Do you find it useful?

I (personally) prefer putting the `noqa` at the end, since if you put it _inside_ the string, then it gets treated as actual string contents. So, e.g., if you include it in a docstring, then when you render the docstrings in other tools, the `noqa` is included.

**Comment by ghuls** [comment]
Indeed you are right that is shows up in rendered doc strings. In that case is indeed not that useful.
