### ISSUE TITLE
C414 fix fails when `sorted()` call has `key` or `reverse` argument

### ISSUE THREAD

**Issue by leos** [charliermarsh/ruff#3913]
ruff version: 0.0.261

`foo.py`:
```
sorted_by_size = sorted(list(sizes.keys()), key=lambda k: -sizes[k])
```

```
> ruff foo.py --fix
error: Failed to create fix: Expected one argument in outer function call
foo.py:2:18: C414 Unnecessary `list` call within `sorted()`
Found 1 error.
```

**Comment by dhruvmanila** [comment]
There are couple more cases related to `sorted` function:

### `sorted` with arguments inside a `set` call:
```python
set(sorted(iterable, key=lambda x: x))

# The above code gets fixed incorrectly to:
set(iterable, key=lambda x: x)
```

### `sorted` with `sorted`

```python
sorted(sorted(iterable, key=lambda x: x))

# The arguments are copied as it is which is incorrect:
sorted(iterable, key=lambda x: x)
```

---

I think an easy fix for now would be to make this violation's `AUTOFIX` to `AutofixKind::Sometimes` and provide a fix only if there are no arguments in both the inner and outer call. Otherwise, if it's easy enough to fix all these cases, that would be preferable.

**Comment by dhruvmanila** [comment]
I think everything can be fixed:

## Proposed solution

* **Author's case**: Preserve the outer call arguments
* **Case 1 & 2**: Do not flag this as error as the inner sorting is done using a key function. A generic way to put this would be to only remove the inner `sorted` call if no arguments are present.

**Comment by leos** [comment]
Thanks for the fix! The weekend isn't even over... now I see why `ruff` is as fast as it is! ⚡
