### ISSUE TITLE
Possible inconsistency with "D" rule parsing docstrings

### ISSUE THREAD

**Issue by syntaxaire** [charliermarsh/ruff#3978]
With ruff 0.0.261, using the "D" rule with  `--fix`, the following code:
```python
"""
Do a fix.
Workaround for:
BUG: https://github.com/someproject/somerepo/issues/1337
"""
```
is autocorrected to:
```python
"""Do a fix.
Workaround for:
BUG: https://github.com/someproject/somerepo/issues/1337.
"""
```
Note the addition of a period in line 3. But inserting a newline into the original code causes that period not to be added:
```python
"""
Do a fix.

Workaround for:
BUG: https://github.com/someproject/somerepo/issues/1337
"""
```
is autocorrected to
```python
"""Do a fix.

Workaround for:
BUG: https://github.com/someproject/somerepo/issues/1337
"""
```
Note the lack of a period after the link.

**Comment by syntaxaire** [comment]
configuration in `pyproject.toml` is:
```
[tool.ruff]
select = [
  "A", "ARG", "B", "BLE", "C4", "C90", "D", "DTZ", "E", "ERA", "F", "FBT", "G", "I", "ISC", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "Q", "RET", "RSE", "RUF", "S", "SIM", "T10", "T20", "TRY", "UP", "W", "YTT"
]

unfixable =  [
  "ERA001",
  "RUF002",
]
```

**Comment by charliermarsh** [comment]
Yeah it's a little challenging to get this right in all cases. Broadly, when checking if the docstring ends in a period, I believe we look for the "summary line", which is considered to be all content up to the first paragraph break.

This is to support docstrings like:

```
"""Here's content and
here's more flowing content onto
the next lines
"""
```

Here, we put the period after `lines`, rather than after `and`. But that clearly leads to strange output in the case above.

**Comment by charliermarsh** [comment]
(Not certain what if anything should change -- previous comment is purely informational for now.)

**Comment by charliermarsh** [comment]
Closing this as "expected" for now.
