### ISSUE TITLE
flake8's (`W503` and) `W504`

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4125]
`flake8` has two rules [`W503`](https://www.flake8rules.com/rules/W503.html) and [`W504`](https://www.flake8rules.com/rules/W504.html) that don't seem to be in `ruff==0.0.263`.
- https://github.com/PyCQA/flake8/issues/494 mentions that `W503` shouldn't exist
- https://stackoverflow.com/questions/73568036/flake8-line-break-before-binary-operator-how-to-fix-it discusses `W503` and `W504`

Any thoughts on `ruff` implementing `W504` with autofix?

**Comment by charliermarsh** [comment]
I think we're unlikely to implement W503 and W504, since we're likely not going to implement the pycodestyle rules that are ignored-by-default (due to being non-unanimously accepted, and non-violations of PEP8, per the [pycodestyle docs](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)).

W503 is a little more problematic, since it conflicts with Black. W504 _might not_ conflict with Black, but I'm still hesitant to support it given that it's disabled-by-default in pycodestyle and Flake8.

**Comment by charliermarsh** [comment]
(As always, totally open to further discussion -- I just tend to close issues by-default when answering a question, to try and manage the issue queue responsibly.)

**Comment by jamesbraza** [comment]
Oh sure, this conclusion is fine with me, thanks!  I realize I have been making a lot of issues here, but it's okay to close them.

For me to remove `flake8`, I want to make sure the rule coverage is the same.  With `W504` dispatched (per this issue), the last outstanding items are:
- `doctests = True`: https://github.com/charliermarsh/ruff/issues/3542
- `flake8-requirements`: https://github.com/charliermarsh/ruff/issues/4100

**Comment by ccostello97** [comment]
@charliermarsh I'd like to propose this be re-opened. Black does take the stance of W504 against line breaks after binary operators, which also aligns with the PEP-8 recommendation.

To keep my code in check with PEP-8, I have to use ruff with `flake8 --select=W504`, it would certainly be nice to have this in ruff.

**Comment by Avasam** [comment]
FWIW, this would also bring Ruff autofixes closer to parity with autopep8, even if ignored/disabled by default https://github.com/astral-sh/ruff/discussions/9057#discussioncomment-7850584

**Comment by zlrabigautam** [comment]
if (
    not token or
    not flag_id or
    not flag_title or
    not description or
    not resource_id
):    

W503 line break before binary operator. How to solve it?

**Comment by andrei-korshikov** [comment]
> we're likely not going to implement the pycodestyle rules that are ignored-by-default (due to being non-unanimously accepted, and non-violations of PEP8, per the [pycodestyle docs](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)).

`W503`/`W504` would not be the only opinionated option in Ruff. E.g. we have `D203`/`D212` and their counterparts, we have some `B9` options (which are disabled by default in the original flake8-bugbear), entire flake8-bandit is highly opinionated, we have `tool.ruff.lint.flake8-quotes.inline-quotes` at the end:))

Of course, running `flake8 --select=W504` is easy (I use flake8 because of `pydoclint` anyway), but, frankly, I was surprised.
