### ISSUE TITLE
There is a string in the first line of the code.  However, ruff raises an error of RUF002 which says "Docstring contains ambiguous unicode character". 

### ISSUE THREAD

**Issue by yuji38kwmt** [charliermarsh/ruff#4267]
# Python code

`sample.py`

```python
"ａ"
a = "ａ"
"ａ"
```

# Command

```
$ ruff check sample.py --select RUF
sample.py:1:2: RUF002 [*] Docstring contains ambiguous unicode character `ａ` (did you mean `a`?)
sample.py:2:6: RUF001 [*] String contains ambiguous unicode character `ａ` (did you mean `a`?)
sample.py:3:2: RUF001 [*] String contains ambiguous unicode character `ａ` (did you mean `a`?)
Found 3 errors.
[*] 3 potentially fixable with the --fix option.
```

# Issue
There is a string in the first line of the code. 
However, when I run Ruff, it raises an error of RUF002 which says "Docstring contains ambiguous unicode character". 
I believe that Ruff should raise an error of RUF001 which says "String contains ambiguous unicode character".

# Settings
no pyproject.toml

# Version

```
$ ruff --version
ruff 0.0.264

```

**Comment by charliermarsh** [comment]
While a bit confusing, I think this might be correct, since Python does consider that top-level string `"a"` to be a docstring.

If you run `help(sample)`:

```
Help on module sample:

NAME
    sample - ａ

DATA
    a = 'ａ'

FILE
    /Users/crmarsh/workspace/ruff/sample.py
```

Notice that the docstring appears after `sample -`. So from Python's perspective, it _is_ a docstring, even if it doesn't seem like one, unless I'm mistaken.
