### ISSUE TITLE
Expected for noqa to be ignored for multi-line string variable?

### ISSUE THREAD

**Issue by fennerm** [charliermarsh/ruff#4484]
(ruff=v0.0.267).

Based on the docs we can add a noqa annotation to a multi-line string as follows:
```
"""
Some long
string.
"""  # noqa
```

I would assume this should also be true if the string is a variable, but the noqa annotation seems to be ignored in that case.

Minimal example:
```
weirdly_Cased: str = """
Some long
string.
"""  # noqa: N816
```

Ruff outputs:
```
N816 Variable `weirdly_Cased` in global scope should not be mixedCase
RUF100 [*] Unused `noqa` directive (unused: `N816`)
```

Possible that this case is deliberately not supported yet but figured I'd flag it. Thanks!

**Comment by charliermarsh** [comment]
Hmm -- I suspect this changed when we did the "byte offset" refactor (\cc @MichaReiser), though I'm torn on what should be considered "correct" here... The motivation for respecting `noqa` directives at the end of multi-line strings is that you can't feasible put a `noqa` directive _within_ a multi-line string (otherwise, it becomes part of the string itself). In this case, you _could_ put the `noqa` here:

```py
weirdly_Cased: str = (  # noqa: N816
    """
Some long
string.
"""
)
```

But, we're clearly not making that change with `--add-noqa`, and it feels somewhat "surprising" that the form you provided above doesn't work.

What do you think, @MichaReiser?

**Comment by MichaReiser** [comment]
I think this is a bug and can probably be fixed by remapping the range from the start of the line instead of the multiline-string ranage only in:

https://github.com/charliermarsh/ruff/blob/ddd541b1987493a69ef5e8f65ef8030eda6198cd/crates/ruff/src/directives.rs#L100-L107

by using `string_mappings.push(TextRange::new(locator.line_start(range.start()), range.end()));`

```py
weirdly_Cased: str = (  # noqa: N816
    """
Some long
string.
"""
)
```

should then continue to work because we only remap the lines of the multiline-string, not the assignment's line
