### ISSUE TITLE
Possible overlap between TRY400 and G201

### ISSUE THREAD

**Issue by ericbn** [charliermarsh/ruff#4603]
#### test.py
Minimal code snipped that reproduces the bug:
```
import logging

logger = logging.getLogger()
try:
    pass
except Exception:
    logger.error("Error", exc_info=True)
```

#### Ruff output

The command I've invoked: `ruff --isolated --select G,TRY test.py`
```
test.py:7:5: TRY400 Use `logging.exception` instead of `logging.error`
test.py:7:12: G201 Logging `.exception(...)` should be used instead of `.error(..., exc_info=True)`
Found 2 errors.
```

After changing the test.py file to:
```diff
-    logger.error("Error", exc_info=True)
+    logger.error("Error")
```
I get only:
```
test.py:7:5: TRY400 Use `logging.exception` instead of `logging.error`
Found 1 error.
```

Maybe the broader TRY400 rule is enough, in favor of G201. Not sure what's the rationale for overlapping/duplicate rules in ruff.

#### ruff --version
```
ruff 0.0.269
```

**Comment by madkinsz** [comment]
Hm `logger.exception` has a different meaning than `logger.error` — `logger.error` does not include a traceback unless `exc_info` is set but `logger.exception` does. I think these rules cover different cases.

- `G201`: If you're going to log a traceback, use `.exception` instead of `.error`
- `TRY400`: If you're going to log an error, always log a traceback

**Comment by charliermarsh** [comment]
Thank you for the extremely clear issue, appreciated as always. I think these are _slightly_ different, but what we _could_ do is change `TRY400` to avoid flagging `logger.error` calls with `exc_info=True`, since those will include a traceback anyway as per the intent of the rule. (Then, suggesting the use of `logging.exception` over `exc_info=True` would be covered separately by `G201`.) What do you think, @madkinsz?
