### ISSUE TITLE
UP035 - option to disable for types that aren't collections

### ISSUE THREAD

**Issue by DetachHead** [charliermarsh/ruff#4699]
there are several types in `collections.abc` that make no sense being there like `Callable`, `Awaitable`, `Coroutine`, so i think they should instead be imported from `typing`.

it would be nice to be able to disable this rule for types like those

**Comment by charliermarsh** [comment]
I understand this perspective, but at the same time, members like `typing.Callable` are officially deprecated since Python 3.9 (see [PEP 585](https://peps.python.org/pep-0585/), or the [`typing` docs](https://docs.python.org/3/library/typing.html#typing.Callable)), and may not even exist in future versions of Python -- so we'd be adding an option to opt-in to ignoring a deprecation based on a disagreement with a change in the standard library. I want to keep a high bar for adding configuration options, and I don't think this would meet that bar.
