### ISSUE TITLE
Suggestion: Full documentation via mdbook

### ISSUE THREAD

**Issue by tgross35** [charliermarsh/ruff#654]
Have you considered adding some documentation outside of the readme, potentially with mdbook?

I ask because the readme page is getting quite lengthy, but could probably use some more detail in places like error code descriptions, command line arguments/config files (with examples) and use with editors.

A structure like [`rustc_error_codes` crate](https://github.com/rust-lang/rust/tree/837bf370de144a682041e68bb67469b9f68a55ce/compiler/rustc_error_codes) might be good to start building. This would enable something like `ruff --explain E123` in the future as well

Is there any interest? If so, I would be willing to get a PR together

**Comment by charliermarsh** [comment]
Yeah this is extremely important! I've been putting it off, but the docs are falling way behind the scope of the project.

I want to be fairly intentional about creating proper docs (need to think on the exact structure and setup a bit more), but I think creating dedicated descriptions for error codes like you've described above (something could power `--explain`) would be a great start. In other words: I don't know exactly where I want the docs to live etc., but something like the `rustc_error_codes` setup looks like it could plug in to a variety of options? I would be happy to start with mdBook too with the caveat that I might move to a different system somewhere down the line (TBD).

PR welcome!

**Comment by tgross35** [comment]
Sounds great! I'll get something going

**Comment by charliermarsh** [comment]
We now have this working (in a basic way):

- https://github.com/charliermarsh/ruff/blob/main/docs/rules/assert-raises-exception.md
- https://beta.ruff.rs/docs/rules/assert-raises-exception/

**Comment by tgross35** [comment]
Oh hey, that's awesome! Sorry I never got around to this, but glad it worked out
