### ISSUE TITLE
Make `combine_as_imports = false` the default sorting behavior

### ISSUE THREAD

**Issue by charliermarsh** [charliermarsh/ruff#705]
This would make our import sorting drop-in compatible with `isort`, but it's a bit more complicated, I don't prefer the behavior, and there are a variety of comments on the `isort` repo suggesting they wanted to make `true` the default anyway.

https://pycqa.github.io/isort/docs/configuration/options.html#combine-as-imports

**Comment by tiangolo** [comment]
I just came to ask for this... I know I said I didn't have a preference, but adding Ruff to FastAPI I just realized I do. 😅

Most of the "import as" I have are just to re-export things from other places, so that mypy and PyRight can know they are available, without having to deal with `__all__` that is much more error prone (strings referring to code can get obsolete and out of sync easily).

And having those "import as" in their own line helps me see more explicitly what are the things that I'm re-exporting and don't get lost among the things I'm just importing to use internally.

**Comment by charliermarsh** [comment]
Yeah makes sense! Will change this. (There’s maybe a case to be made that “from a import b as b” and “from a import b as c” should get different treatment, but probably worth just being drop-in compatible with isort at this point.)

**Comment by Jackenmen** [comment]
> This would make our import sorting drop-in compatible with `isort`, but it's a bit more complicated, I don't prefer the behavior, and there are a variety of comments on the `isort` repo suggesting they wanted to make `true` the default anyway.

@charliermarsh is there an option for combining `as` imports available? It doesn't seem to based on the documentation and the PR that closed this issue but I'm finding that surprising considering that you said you prefer it :thinking:
For what it's worth, I also prefer it and it's the only discrepancy from the default `black` profile in all projects where I have isort set up.

**Comment by charliermarsh** [comment]
@Jackenmen - Yeah I ended up changing the default behavior and didn't think it was worth making it configurable, but I can probably support it. Will take a look...

**Comment by charliermarsh** [comment]
@Jackenmen - I've implemented it here: https://github.com/charliermarsh/ruff/pull/1022. Will go out shortly. Can you give it a try and let me know if it matches your expectation?

**Comment by Jackenmen** [comment]
It appears to work as I expect, checked first on one made-up example and then on two isorted codebases.
