### ISSUE TITLE
feature: fix-exclude?

### ISSUE THREAD

**Issue by tlambert03** [charliermarsh/ruff#786]
first: ruff is freakin amazing and incredibly helpful.  _thank you_ for your work.

Apologies if this already exists and I missed it when searching:  I regularly use the `--fix` feature with pre-commit, but would like to be able to exclude certain rules from fixing, while still having them raise an error (for me to manually correct).  

For example, I'd like `F401` to be excluded from autocorrection.  I'm aware that I could do something like `per-file-ignores = {"__init__.py" = ["F401"]}` to avoid fixing it, but then it won't alert me to them either.

Is this possible?

thanks!

**Comment by charliermarsh** [comment]
Having trouble with the name of this option. I think `fix-exclude` might be confusing because in the language of the configuration file, `exclude` already refers to _files_ to omit. `no-fix` could be ok, but it's similar to `--no-fix` which is the command-line flag to force-disable all fixing.

I almost want `dont-fix`? But grammatically weird with the abbreviation. `skip-fix`?

**Comment by tlambert03** [comment]
fantastic! thank you!

That turn around time was rust-fast ;)

**Comment by charliermarsh** [comment]
Let me know if that interface works for you! It's documented a bit in the https://github.com/charliermarsh/ruff/pull/811 summary. (We desperately need proper docs for all the configuration settings!)

**Comment by tlambert03** [comment]
yep, `unfixable` works fine for me.  will play after the release finishes building
