### ISSUE TITLE
U007 Autofix on string type format

### ISSUE THREAD

**Issue by martinlehoux** [charliermarsh/ruff#826]
I have an issue with U007 autofix, but I can't really say if it's a bug or not.

I have this piece of code (the `if TYPE_CHECKING:` is required for cyclic imports issue)

```py
if TYPE_CHECKING:
    from app.models.model_a import ModelA
    from app.models.model_b import ModelB

ModelAOrB = Union["ModelA", "ModelB"]
```

and it gets fixed into

```py
if TYPE_CHECKING:
    from app.models.model_a import ModelA
    from app.models.model_b import ModelB

ModelAOrB = "ModelA" | "ModelB"
```

which is not the same type as before

**Comment by martinlehoux** [comment]
That being said, maybe it's not the way to do types, and if it's just a workaround I need, I can simply ignore this check on this specific line

**Comment by martinlehoux** [comment]
That being said, maybe it's not the way to do types, and if it's just a workaround I need, I can simply ignore this check on this specific line

**Comment by charliermarsh** [comment]
Ohh interesting, yeah that's a bug. According to [this issue](https://bugs.python.org/issue45857), you're expected to instead do `ModelAOrB = "ModelA | ModelB"`.

**Comment by charliermarsh** [comment]
It looks like pyupgrade [skips those altogether](https://github.com/asottile/pyupgrade/blob/5b527acec11568ee095181a333adaaa1fec9fe27/pyupgrade/_plugins/typing_pep604.py#L147).

**Comment by hmc-cs-mdrissi** [comment]
If you want the whole string then whether it’s a string or a type alias becomes more ambiguous and behavior may vary by type checker. The recommendation there is to do,

ModelAorB: TypeAlias = “ModelA | ModelB”

This may require adding an import to TypeAlias with additional caveat the TypeAlias is only a thing since 3.10 or if you use typing extensions. It’s probably safest to just skip this case like pyupgrade unless you plan to add the correct import depending on python version/environment.

**Comment by charliermarsh** [comment]
@hmc-cs-mdrissi - Yeah totally agree -- I think we need to just skip the upgrade in that case. (`"ModelA | ModelB"` is also much more confusing IMO than the same type expressed as a `Union`.)
