### ISSUE TITLE
What does Ruff stands for?

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#865]
RUst Fast Flake8?

**Comment by charliermarsh** [comment]
Something like that! It doesn't officially stand for anything, but I did want something that somehow incorporated Rust and Flake phonetically. I also liked that Ruff is: (1) very easy to type (helpful for a command-line tool); and (2) a homophone of "rough", since I released it in a very rough state to start.

Just for fun, here's the list of names I considered (most of them are bad):

- pyretic
- rake8
- pylion
- clippy
- pinprick
- pyfragment
- cake8
- iflake
- flakes
- malaz
- pippy
- pyclip
- pyclippy
- obscura
- miracle
- flinty
- maw
- flak
- ruff
- ruffle
- raffle
- tussle
- scuffle
- onyxia
- carthage
- roxy
- roxide
- rooky
- flake
- fluke
- flank
- flaunt
- fermyon
- oxyde
- oxigen
- ferric
- roxigen
- flynter
- fyn

**Comment by lolrenx** [comment]
rake8 cracked me up
