### ISSUE TITLE
F401 column number is imprecise

### ISSUE THREAD

**Issue by relsunkaev** [charliermarsh/ruff#946]
When some of the `from` statement's imports are unused, ruff highlights the entire statement. For large, multi-line imports this creates a lot of noise when using an extension to highlight errors in the editor and it may be better for the error to point to the exact imports that are unused instead.

Example:
```python
from typing import (
    Any,
    Awaitable,
    Hashable,
    Iterable,
    Mapping,
    Sequence,
    TypeAlias,
    TypedDict,
)

SomeAlias = Mapping[str, str] | Sequence[str] | Iterable[str] | Awaitable[str]
```

Will generate

```
example.py:1:1: F401 `typing.Any`, `typing.TypedDict` imported but unused
```

This would probably require reporting each unused import separately though. I'm willing to take a stab at a PR but was wondering if this change is unwelcome/unwanted by the maintainers.

**Comment by charliermarsh** [comment]
Yeah this could definitely be improved. IIRC, I implemented it this way to make autofixing easier and more reliable. But now that we support iterative autofix, it might be fine to revert back to "one error per unused import".

It may not be trivial, though, since we'll have to do some bookkeeping as we autofix, since we want to avoid leaving around empty statements like:

```py
from typing import (
)
```

**Comment by charliermarsh** [comment]
The downside is that if we mark each member as its own error, then if you were to trigger an "autofix" for that error (e.g., in the VS Code UI), you'd have to repeat that action for each member.

**Comment by charliermarsh** [comment]
Oh yeah, that seems reasonable!

**Comment by charliermarsh** [comment]
PR welcome for that change if you’re up for it — otherwise I’ll get to it at some point :)
