### ISSUE TITLE
Consider adding `keep-runtime-typing` or equivalent option for `pyupgrade` rules

### ISSUE THREAD

**Issue by layday** [charliermarsh/ruff#962]
pyupgrade allows opting out of upgrading `typing` aliases of built-in collections and `typing.Union`s if they are used at runtime (e.g. by libraries such as Pydantic and cattrs) in Python versions in which they are unsupported if not stringified (< 3.9 for the former and < 3.10 for the latter).  It would be great if ruff could provide an equivalent option so that we are able to adopt the new syntax upon upgrading Python, without having to ignore the rules (and later forget to unignore them).

**Comment by charliermarsh** [comment]
Can do!

**Comment by charliermarsh** [comment]
Added in https://github.com/charliermarsh/ruff/pull/965. I mirrored pyupgrade's behavior, which is that if you target Python 3.9, we still make those upgrades even if you passed in `--keep-runtime-typing` -- so that setting is only applicable when `--target-version` is 3.7 or 3.8, and you've imported `from __future__ import annotations` .
